Default: &defaults
  user: george
  password:
  host: localhost
  port: 5432
  database: todohs
  poolsize: 10

Development:
  <<: *defaults

Test:
  database: todohs_test
  <<: *defaults

Staging:
  database: todohs_staging
  poolsize: 100
  <<: *defaults

Production:
  database: todohs_production
  poolsize: 100
  <<: *defaults
